// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXrnSMLwY8SGDxYL15lkEOm4LWCZef2yw',
    appId: '1:495471679247:web:6d9382965d2344767bd07a',
    messagingSenderId: '495471679247',
    projectId: 'flutter-chatapp-6b739',
    authDomain: 'flutter-chatapp-6b739.firebaseapp.com',
    storageBucket: 'flutter-chatapp-6b739.firebasestorage.app',
    measurementId: 'G-SY7YPQB9MM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkWiWMnJoNbCLKfq_6JrE3g2_TwGeBmVY',
    appId: '1:495471679247:android:f37d0d2dcccf96487bd07a',
    messagingSenderId: '495471679247',
    projectId: 'flutter-chatapp-6b739',
    storageBucket: 'flutter-chatapp-6b739.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXdQOfA33WUoCK5jxXN9jM7iTa3H7jOWw',
    appId: '1:495471679247:ios:5b77c24874080f007bd07a',
    messagingSenderId: '495471679247',
    projectId: 'flutter-chatapp-6b739',
    storageBucket: 'flutter-chatapp-6b739.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXdQOfA33WUoCK5jxXN9jM7iTa3H7jOWw',
    appId: '1:495471679247:ios:5b77c24874080f007bd07a',
    messagingSenderId: '495471679247',
    projectId: 'flutter-chatapp-6b739',
    storageBucket: 'flutter-chatapp-6b739.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXrnSMLwY8SGDxYL15lkEOm4LWCZef2yw',
    appId: '1:495471679247:web:fb213a154122d3cf7bd07a',
    messagingSenderId: '495471679247',
    projectId: 'flutter-chatapp-6b739',
    authDomain: 'flutter-chatapp-6b739.firebaseapp.com',
    storageBucket: 'flutter-chatapp-6b739.firebasestorage.app',
    measurementId: 'G-5P3DYMXPVE',
  );

}